"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os  # Added for path joining
from pathlib import Path
from dotenv import load_dotenv  # ADDED: To read the .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ADDED: This triggers the reading of your .env file
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# UPDATE: Uses environment variable for production, falls back to your current key for local dev.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-avi+hw#p9q9!w0$baygtt4)edj=8k)n__^gnxlgq9@x^zp64g=')

# SECURITY WARNING: don't run with debug turned on in production!
# UPDATE: Defaults to True locally, set DJANGO_DEBUG to 'False' on your hosting platform.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# UPDATE: Added common hosting domains, local addresses, and your custom Ghanaian domain
ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    'finance.edu.gh', 
    'www.finance.edu.gh', 
    '.herokuapp.com', 
    '.pythonanywhere.com'
]


# --- ADDED: PRODUCTION SECURITY HEADERS ---
# These settings only activate when DEBUG is False to satisfy the security check.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000 # 1 Year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'invoices',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # ADDED: Required for serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.media', # Added for media access in templates
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # ADDED: This allows {{ config }} to work in all templates
                'invoices.context_processors.system_config', 
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- FIXED: Pointing to invoices/static where your 1.png is located ---
STATICFILES_DIRS = [
    BASE_DIR / "invoices" / "static",
]

# ADDED FOR DAISYUI: Ensure static files can be collected for the modern theme
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ADDED: Whitenoise storage for compression and caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- MEDIA FILES (Uploaded Student Photos) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# --- UPDATED AUTH SECTION ---
LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- REAL EMAIL CONFIGURATION ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nanayeezy@gmail.com' 
# UPDATE: Pulled from the .env file for security
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') 
DEFAULT_FROM_EMAIL = 'nanayeezy@gmail.com'

# --- DAISYUI THEME SETTINGS ---
# This tells our future templates to use the 'cupcake' or 'business' theme logic
DAISYUI_THEME = "light"